[2024-09-27 00:26:16,921] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.42.53:8000
[2024-09-27 00:26:16,921] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-09-27 00:26:19,625] 838 app - ERROR - Exception on /predict [GET]
Traceback (most recent call last):
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Varun\Music\Python\ProjectOne\app.py", line 11, in prdict_datapoint
    return render_template('form.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\Varun\Music\Python\ProjectOne\templates\form.html", line 3, in top-level template code
    <form action="{{url_for('predict_datapoint')}}" method="POST">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict_datapoint'. Did you mean 'prdict_datapoint' instead?
[2024-09-27 00:26:19,642] 97 werkzeug - INFO - 127.0.0.1 - - [27/Sep/2024 00:26:19] "[35m[1mGET /predict HTTP/1.1[0m" 500 -
[2024-09-27 00:27:11,878] 838 app - ERROR - Exception on /predict [GET]
Traceback (most recent call last):
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Varun\Music\Python\ProjectOne\app.py", line 11, in prdict_datapoint
    return render_template('form.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\Varun\Music\Python\ProjectOne\templates\form.html", line 3, in top-level template code
    <form action="{{url_for('predict_datapoint')}}" method="POST">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict_datapoint'. Did you mean 'prdict_datapoint' instead?
[2024-09-27 00:27:11,880] 97 werkzeug - INFO - 127.0.0.1 - - [27/Sep/2024 00:27:11] "[35m[1mGET /predict HTTP/1.1[0m" 500 -
[2024-09-27 00:28:06,670] 838 app - ERROR - Exception on /predict [GET]
Traceback (most recent call last):
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Varun\Music\Python\ProjectOne\app.py", line 11, in prdict_datapoint
    return render_template('form.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\Varun\Music\Python\ProjectOne\templates\form.html", line 3, in top-level template code
    <form action="{{url_for('predict_datapoint')}}" method="POST">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict_datapoint'. Did you mean 'prdict_datapoint' instead?
[2024-09-27 00:28:06,680] 97 werkzeug - INFO - 127.0.0.1 - - [27/Sep/2024 00:28:06] "[35m[1mGET /predict HTTP/1.1[0m" 500 -
