[2024-09-27 00:51:57,057] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.42.53:8000
[2024-09-27 00:51:57,057] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-09-27 00:52:01,964] 63 root - INFO - Dataframe Gathered
[2024-09-27 00:52:02,045] 46 root - INFO - Exception occured in load_object function
[2024-09-27 00:52:02,045] 838 app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "c:\Users\Varun\Music\Python\ProjectOne\src\utility\utility.py", line 43, in load_object
    with open(file_path,'rb') as file_obj:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\model.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Varun\Music\Python\ProjectOne\src\pipeline\prediction_pipeline.py", line 17, in predict
    model=load_object(model_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Varun\Music\Python\ProjectOne\src\utility\utility.py", line 47, in load_object
    raise customexception(e,sys)
src.exceptions.exceptions.customexception: Error occurred in python script name [c:\Users\Varun\Music\Python\ProjectOne\src\utility\utility.py] line number [43] error message [[Errno 2] No such file or directory: 'artifacts\\model.pkl']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Varun\Music\Python\ProjectOne\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Varun\Music\Python\ProjectOne\app.py", line 28, in predict_datapoint
    pred=predict_pipeline.predict(final_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Varun\Music\Python\ProjectOne\src\pipeline\prediction_pipeline.py", line 25, in predict
    raise customexception(e,sys)
src.exceptions.exceptions.customexception: Error occurred in python script name [c:\Users\Varun\Music\Python\ProjectOne\src\pipeline\prediction_pipeline.py] line number [17] error message [Error occurred in python script name [c:\Users\Varun\Music\Python\ProjectOne\src\utility\utility.py] line number [43] error message [[Errno 2] No such file or directory: 'artifacts\\model.pkl']]
[2024-09-27 00:52:02,048] 97 werkzeug - INFO - 127.0.0.1 - - [27/Sep/2024 00:52:02] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
